const fs = require('fs');
const content = fs.readFileSync('index.html', 'utf-8');

const match = content.match(/const plants=\[([\s\S]*?)\];/);
if (!match) { console.log('ERROR: no plants array'); process.exit(1); }

let plantsText = match[1];

// Parse existing entries by brace depth
const entries = [];
let depth = 0, current = '', inStr = false, strCh = '', esc = false;

for (let i = 0; i < plantsText.length; i++) {
  const ch = plantsText[i];
  if (esc) { current += ch; esc = false; continue; }
  if (ch === '\\') { current += ch; esc = true; continue; }
  if (!inStr && (ch === '"' || ch === "'" || ch === '`')) {
    inStr = true; strCh = ch; current += ch; continue;
  }
  if (inStr && ch === strCh) { inStr = false; strCh = ''; current += ch; continue; }
  if (!inStr) {
    if (ch === '{') {
      if (depth === 0) current = '';
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) {
        current += ch;
        const entry = current.trim();
        if (entry) entries.push(entry);
        current = '';
        continue;
      }
    }
  }
  current += ch;
}

console.log('Existing entries:', entries.length);

// New plants to add
const newPlants = [
{id:242,cn:"Sedum rubrotinctum",la:"Jelly Bean Plant",light:"Requires bright light for at least 6 hours daily to maintain compact shape and red coloration. A south-facing window is ideal. In low light, the plant stretches and turns entirely green.",water:"Water thoroughly only when soil is completely dry, typically every 2–3 weeks. Drought-tolerant and prone to rot if kept wet. Reduce significantly in winter.",temp:"Prefers 65–75°F (18–24°C). Tolerates brief dips to 25°F (-4°C) but bring indoors if freezing is expected.",soil:"Use a gritty, fast-draining succulent mix with extra perlite. A terracotta pot with drainage holes is essential.",fert:"Fertilize sparingly — once each in spring and fall with a diluted succulent fertilizer at quarter strength.",rep:"Repot every 1–2 years in spring. Handle fragile leaves carefully as they detach easily.",growth:"A trailing succulent with plump, bean-shaped leaves that turn from green to vivid red with sun exposure and temperature changes. Produces yellow star-shaped flowers in spring.",problems:["Sun stress is beneficial; strong light and slight underwatering create the red tips","Fallen leaves root easily on the soil surface","Green coloring indicates insufficient light","Mushy leaves indicate overwatering"],tox:"Mildly toxic to pets if ingested, causing vomiting and lethargy. Generally safe for humans.",prop:"Extremely easy. Fallen leaves root on their own. Place healthy leaves on dry succulent mix and mist lightly."},
{id:260,cn:"Cotyledon tomentosa",la:"Bear's Paw",light:"Prefers bright indirect light with some gentle morning sun. An east-facing window is ideal. Avoid harsh afternoon sun which can scorch the fuzzy leaves. At least 4 hours of bright light daily.",water:"Water when soil is completely dry, typically every 2–3 weeks. Use the soak-and-dry method. Avoid getting water on the fuzzy leaves. Reduce significantly in summer dormancy.",temp:"Prefers 50–80°F (10–27°C). Protect from frost and temperatures below 32°F (0°C). Good air circulation is important.",soil:"Use a fast-draining succulent or cactus mix with extra perlite or pumice. A terracotta pot with drainage holes is ideal.",fert:"Feed with a diluted succulent fertilizer at quarter strength monthly during spring and fall. Do not fertilize in summer or winter.",rep:"Repot every 1–2 years in spring. Handle the fuzzy leaves very gently to avoid damage.",growth:"A charming succulent with thick, oval leaves covered in fine white fuzz, resembling tiny bear paws. Leaf tips may develop reddish-brown claws. Reaches 6–12 inches tall.",problems:["Fuzzy leaves should not get wet; water the soil directly","Leaf fuzz damage does not regenerate; handle with extreme care","Reduce watering during summer dormancy to prevent rot","Mealybugs may hide in the fuzz; inspect carefully"],tox:"Mildly toxic to pets and humans if ingested, causing gastrointestinal upset.",prop:"Propagate from stem cuttings. Take a 3–4 inch cutting, let callus for 3–5 days, then plant in dry succulent mix. Wait 1–2 weeks before watering."},
{id:261,cn:"Crassula 'Morgan's Beauty'",la:"Morgan's Beauty",light:"Requires bright light for at least 5–6 hours daily. A south- or west-facing window is ideal. Strong light enhances the silvery-blue leaf color and compact growth. Insufficient light causes stretching.",water:"Use the soak-and-dry method. Water deeply, then wait until soil is completely dry before watering again (typically 2–3 weeks). Reduce significantly in winter.",temp:"Prefers 55–80°F (13–27°C). Protect from temperatures below 32°F (0°C) and frost.",soil:"Use a fast-draining succulent or cactus mix with added perlite or pumice. A terracotta pot with drainage holes is ideal.",fert:"Feed with a diluted succulent fertilizer at quarter strength once in spring and once in fall. Avoid over-fertilizing.",rep:"Repot every 1–2 years in spring. Handle leaves gently as they can rub off easily.",growth:"A striking hybrid succulent with thick, overlapping, silvery-blue leaves arranged in a tight rosette. Reaches 2–3 inches across. Growth is slow. The waxy coating (farina) protects from sunburn.",problems:["The farina (white powdery coating) should not be touched off; handle by the pot","Leggy growth indicates insufficient light","Mushy leaves indicate overwatering","Mealybugs hide between leaves; treat with alcohol swabs"],tox:"Non-toxic to cats, dogs, and humans. Safe for households with pets.",prop:"Propagate from offsets or stem cuttings. Separate offsets with some roots and plant in dry succulent mix. Leaf cuttings are also possible. Allow cut ends to callus for 2–3 days."},
{id:262,cn:"Aloe barbadensis miller",la:"Aloe Vera",light:"Requires bright, indirect light for 6–8 hours daily. An east- or south-facing window is ideal. Tolerates some direct morning sun. Too much direct afternoon sun can cause leaf browning.",water:"Drought-tolerant; water every 2–3 weeks when soil is completely dry. Allow excess to drain completely. Overwatering causes mushy, translucent leaves and root rot. Reduce significantly in winter.",temp:"Prefers 55–80°F (13–27°C). Protect from temperatures below 40°F (4°C) and frost. Not cold-hardy.",soil:"Use a fast-draining cactus or succulent mix with added perlite or coarse sand. Excellent drainage is critical. A terracotta pot is ideal.",fert:"Feed with a diluted succulent fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring or when offsets crowd the pot. Choose a pot only slightly wider. Use fresh, well-draining mix.",growth:"A medicinal succulent with thick, fleshy, lance-shaped leaves arranged in a rosette. The clear gel inside leaves has soothing and healing properties. Can reach 1–2 feet tall. Produces offsets (pups) around the base.",problems:["Brown or red leaf tips may indicate too much sun; move to brighter indirect light","Mushy, translucent leaves indicate overwatering; stop watering immediately","Outer leaves drying and shriveling is normal aging","Aloe vera gel can soothe minor burns and skin irritation"],tox:"The gel inside leaves is safe for topical use. However, the latex (yellow sap under the skin) is toxic if ingested, causing cramping and diarrhea. Keep away from pets.",prop:"Very easy to propagate from offsets (pups). Gently separate pups with some roots and plant in dry succulent mix. Wait 1 week before watering. Leaf cuttings are unreliable."},
{id:263,cn:"Crassula ovata",la:"Jade Plant",light:"Requires bright, indirect light for at least 4–6 hours daily. A south- or west-facing window is ideal. Tolerates some direct sun. Too little light causes leggy growth and leaf drop.",water:"Drought-tolerant; water every 2–3 weeks using the soak-and-dry method. Allow soil to dry completely between waterings. Reduce significantly in winter. Overwatering is the primary killer.",temp:"Prefers 55–80°F (13–27°C). Protect from temperatures below 40°F (4°C) and frost. Tolerates dry air well.",soil:"Use a fast-draining cactus or succulent mix with added perlite or pumice. A terracotta pot with drainage holes is ideal.",fert:"Feed with a diluted succulent fertilizer at quarter strength monthly during spring and summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Handle brittle branches carefully. Older plants develop thick, gnarled trunks.",growth:"A long-lived succulent shrub with thick, jade-green, oval leaves on sturdy branches. Also known as the Money Plant. Can reach 2–4 feet indoors and live for decades. May produce clusters of small white or pink flowers after years of care.",problems:["Mushy, translucent leaves indicate overwatering; stop watering immediately","Wrinkled leaves with dry soil indicate thirst","Leggy growth means the plant needs more light","White, cottony masses are mealybugs; treat with alcohol swabs"],tox:"Mildly toxic to cats and dogs if ingested, causing vomiting and incoordination. Generally safe for humans.",prop:"Very easy to propagate from stem or leaf cuttings. Take a 3–4 inch stem cutting or a single leaf, let callus for 2–3 days, then place on dry cactus mix. Mist lightly."},
{id:264,cn:"Graptopetalum amethystinum",la:"Peach Eggs",light:"Requires bright light for at least 5–6 hours daily. A south-facing window is ideal. Strong light enhances the pink-purple leaf coloration. Insufficient light causes stretching and green leaves.",water:"Use the soak-and-dry method. Water deeply, then wait until soil is completely dry before watering again (typically 2–3 weeks). Reduce significantly in winter.",temp:"Prefers 55–80°F (13–27°C). Protect from temperatures below 32°F (0°C) and frost. Tolerates dry air well.",soil:"Use a fast-draining succulent mix with extra perlite or pumice. A terracotta pot with drainage holes is essential.",fert:"Feed with a diluted succulent fertilizer at quarter strength once in spring. Avoid over-fertilizing.",rep:"Repot every 1–2 years in spring. Use fresh succulent mix. Handle plump leaves gently.",growth:"A rosette-forming succulent with plump, rounded leaves in shades of lavender, pink, and gray. Leaves resemble peach-colored eggs. Reaches 4–6 inches across. Growth is slow. Produces offsets around the base.",problems:["Color intensity depends on sun exposure; more sun produces pinker leaves","Wrinkled leaves indicate underwatering","Mushy leaves indicate overwatering","Mealybugs may hide between leaves; treat with alcohol swabs"],tox:"Non-toxic to cats, dogs, and humans. Safe for households with pets.",prop:"Propagate from leaf cuttings or offsets. Gently twist off a healthy leaf, let callus for 2–3 days, then place on dry succulent mix. Roots develop in 2–4 weeks."},
{id:422,cn:"Sempervivum tectorum",la:"Hens and Chicks",light:"Requires full sun for at least 6 hours daily. A south-facing window or outdoor location is ideal. Tolerates intense direct sun. Insufficient light causes open, stretched rosettes.",water:"Drought-tolerant; water every 2–3 weeks when soil is completely dry. Overwatering is the primary killer. Reduce significantly in winter. Avoid getting water in the rosette center.",temp:"Extremely cold-hardy; tolerates temperatures down to -30°F (-34°C). Thrives in a wide range of conditions. One of the most cold-tolerant succulents.",soil:"Use a very fast-draining succulent or gritty mix with extra perlite and sand. Excellent drainage is critical. A shallow terracotta pot works well.",fert:"Rarely needs fertilizer. If desired, apply a very dilute succulent fertilizer once in spring. Over-fertilizing causes weak growth.",rep:"Repot every 2–3 years when soil breaks down. This plant spreads by producing offsets (chicks) that fill the pot. Divide clumps as needed.",growth:"A hardy, rosette-forming succulent that produces numerous offsets (chicks) around the mother plant (hen). Rosettes are compact, reaching 2–4 inches across. After several years, the mother rosette sends up a flower stalk, blooms, and dies — but the chicks survive. Extremely tough and low-maintenance.",problems:["Extremely cold-hardy; can survive outdoors in most climates","The mother plant dies after flowering but produces many offsets before that","Leggy flower stalk means the plant is about to bloom; enjoy the flowers","Overwatering causes rot; when in doubt, do not water","Mealybugs may hide between leaves"],tox:"Non-toxic to cats, dogs, and humans. Safe for households with pets.",prop:"Extremely easy. Simply pull off a chick (offset) with some roots attached and plant in dry succulent mix. Water after 2–3 days. Chicks root quickly in 1–2 weeks."},
{id:423,cn:"Myrtillocactus geometrizans f. monstrosus",la:"Crested Blue Myrtle Cactus",light:"Requires full sun for at least 6–8 hours daily. A south-facing window is ideal. More sun produces bluer stems. Tolerates intense direct sun once acclimated.",water:"Water every 2–3 weeks when soil is completely dry. Reduce significantly in winter. Overwatering causes soft, mushy stems and root rot.",temp:"Prefers 65–85°F (18–29°C). Protect from temperatures below 25°F (-4°C) and frost. Not cold-hardy.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A terracotta pot with drainage holes is essential.",fert:"Feed with a diluted cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Handle spines with care using thick gloves or newspaper. Use fresh cactus mix.",growth:"A striking, crested (monstrose) form of the Blue Myrtle Cactus with fan-shaped, blue-green stems that grow in irregular, undulating patterns. The crested growth is caused by a genetic mutation. Can reach 1–2 feet tall and wide. Growth is slow. The blue waxy coating (farina) is natural and protects from sunburn.",problems:["The crested form is a genetic mutation; normal growth may appear alongside crested growth","The blue farina should not be touched off","Soft, mushy areas indicate overwatering or rot; cut away affected tissue","Spider mites may appear in dry conditions; increase air circulation"],tox:"Mildly toxic if ingested. Spines can cause injury. Keep away from pets and children.",prop:"Propagate from cuttings of the crested portion. Cut a healthy section, let it callus for 1–2 weeks, then plant in dry cactus mix. Water sparingly until roots establish."},
{id:424,cn:"Euphorbia obesa",la:"Baseball Plant",light:"Requires bright, indirect light for 4–6 hours daily. An east-facing window is ideal. Tolerates some gentle direct morning sun. Too much intense sun can cause scarring.",water:"Water every 2–3 weeks when soil is completely dry. Reduce significantly in winter. Overwatering causes soft, mushy body and root rot.",temp:"Prefers 65–80°F (18–27°C). Protect from temperatures below 50°F (10°C) and cold drafts.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A small pot that fits the plant snugly is ideal.",fert:"Feed with a diluted cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Use fresh cactus mix. Handle carefully to avoid scarring the plant body.",growth:"A rare, spherical succulent that resembles a baseball or sea urchin. The body is ribbed with subtle brown and green banding. Growth is extremely slow — the plant may only add 1 inch per year. Can reach 6–8 inches tall and wide over many years. Produces small, inconspicuous flowers at the apex. Dioecious (separate male and female plants).",problems:["Growth is extremely slow; be patient","Scars on the body do not heal; handle with care","Soft or mushy body indicates overwatering; stop immediately","This plant is often sold grafted onto other Euphorbia species for easier care"],tox:"The milky white sap is highly irritating to skin and eyes. Wear gloves when handling. Toxic to pets and humans if ingested.",prop:"Propagate from seed (requires both male and female plants for pollination). Hand-pollinate flowers and sow seeds in moist cactus mix. Seed propagation is slow but the primary method."},
{id:425,cn:"Ferocactus latispinus",la:"Devil's Tongue Barrel",light:"Requires full sun for at least 6–8 hours daily. A south-facing window or outdoor location is ideal. More sun produces stronger, more colorful spines.",water:"Water every 2–3 weeks when soil is completely dry. Reduce to once a month or less in winter. Overwatering causes soft, mushy body and root rot.",temp:"Prefers 65–95°F (18–35°C). Tolerates heat well. Protect from temperatures below 25°F (-4°C) and frost.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A terracotta pot with drainage holes is essential.",fert:"Feed with a cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Handle with extreme care — the spines are very sharp and hooked. Use thick gloves or a folded towel.",growth:"A barrel cactus with a single, globe-shaped stem reaching 12–16 inches tall and wide. Features prominent, hooked, reddish-brown central spines that resemble a devil's tongue. Growth is slow. Produces yellow or red flowers at the apex in summer on mature specimens.",problems:["Spines are extremely sharp and hooked; handle with thick gloves","Soft or mushy body indicates overwatering","Brown spots at the base may indicate age or root rot; check drainage","Mealybugs may hide in the wool at the apex; treat with alcohol swabs"],tox:"Non-toxic to humans and pets. However, the sharp spines can cause injury. Keep away from pets and children.",prop:"Propagate from seed. Sow seeds in moist cactus mix and keep warm. Germination takes 2–4 weeks. Seedlings grow slowly."},
{id:426,cn:"Melocactus",la:"Turk's Cap Cactus",light:"Requires full sun for at least 6–8 hours daily. A south-facing window or outdoor location is ideal. More sun produces a larger cephalium and encourages flowering.",water:"Water every 2–3 weeks when soil is completely dry. Reduce in winter. Overwatering causes soft, mushy body and root rot.",temp:"Prefers 65–85°F (18–29°C). Protect from temperatures below 50°F (10°C) and cold drafts. Not cold-hardy.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A terracotta pot with drainage holes is essential.",fert:"Feed with a cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Handle with care to avoid damaging spines. Use fresh cactus mix.",growth:"A distinctive barrel cactus that develops a woolly, bristly structure called a cephalium at the apex once it reaches maturity (typically 5–10 years). The cephalium is where flowers and fruit emerge. The body is ribbed with curved spines. Growth is slow to moderate.",problems:["The cephalium is a sign of maturity; it takes years to develop","Do not damage the cephalium; it is the flowering structure","Soft body indicates overwatering","Mealybugs may hide in the cephalium wool; treat with alcohol swabs"],tox:"Non-toxic to humans and pets. Spines can cause injury. Keep away from pets and children.",prop:"Propagate from seed. Sow seeds in moist cactus mix and keep warm. Germination takes 2–4 weeks. Seedlings grow slowly."},
{id:427,cn:"Echinocereus rigidissimus",la:"Rainbow Cactus",light:"Requires full sun for at least 6–8 hours daily. A south-facing window or outdoor location is ideal. More sun produces more vibrant spine colors (pink, red, white, yellow bands).",water:"Water every 2–3 weeks when soil is completely dry. Reduce to once a month or less in winter. Overwatering causes soft, mushy body and root rot.",temp:"Prefers 65–85°F (18–29°C) during growth. Cold-hardy to 10°F (-12°C) when kept completely dry in winter. Requires a cool, dry winter dormancy.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A terracotta pot with drainage holes is essential.",fert:"Feed with a cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Handle with care — spines are sharp. Use fresh cactus mix.",growth:"A stunning, slow-growing cactus with cylindrical stems covered in bands of colorful spines (pink, red, white, and yellow). The rainbow-like spine pattern is its most distinctive feature. Produces large, showy pink to purple flowers in spring on mature specimens. Reaches 6–12 inches tall.",problems:["Spine color intensity depends on sun exposure; more sun produces brighter bands","Cold, dry winter dormancy is required for flowering","Soft or mushy body indicates overwatering","Spider mites may appear in dry conditions; increase air circulation"],tox:"Non-toxic to humans and pets. Spines can cause injury. Keep away from pets and children.",prop:"Propagate from seed. Sow seeds in moist cactus mix and keep warm. Germination takes 2–4 weeks. Seedlings grow slowly."},
{id:428,cn:"Gymnocalycium",la:"Chin Cactus / Moon Cactus",light:"Prefers bright, indirect light. Tolerates some gentle morning sun. Avoid harsh afternoon sun which can cause scarring. An east- or north-facing window is ideal.",water:"Water every 2–3 weeks when soil is completely dry. Reduce in winter. Overwatering causes soft, mushy body and root rot.",temp:"Prefers 65–80°F (18–27°C). Protect from temperatures below 40°F (4°C) and frost. Most species are not cold-hardy.",soil:"Use a fast-draining cactus mix with added perlite. Ensure the pot has drainage holes.",fert:"Feed with a diluted cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Use fresh cactus mix. Handle with care to avoid damaging spines.",growth:"A diverse genus of small, globe-shaped cacti with smooth, rounded ribs and chin-like tubercles beneath the areoles (hence the name). Many species produce colorful flowers (pink, white, red, yellow) that emerge from the sides. Moon cacti are Gymnocalycium grafted onto Hylocereus rootstock, creating the colorful, spineless forms. Growth is slow.",problems:["Moon cacti (grafted, colorful forms) have a limited lifespan of 2–5 years; the scion cannot photosynthesize without the rootstock","Non-grafted Gymnocalycium are much longer-lived and easier to care for","Soft or mushy body indicates overwatering","Mealybugs may hide in the wool at the apex"],tox:"Non-toxic to humans and pets. Spines can cause injury. Keep away from pets and children.",prop:"Propagate from offsets or seed. Offsets can be separated and planted in dry cactus mix. Grafting is used for colorful, non-photosynthetic varieties."},
{id:429,cn:"Echinopsis pachanoi",la:"San Pedro Cactus",light:"Requires full sun for at least 6–8 hours daily. A south-facing window or outdoor location is ideal. Acclimate gradually to prevent sunburn.",water:"Water every 2–3 weeks when soil is completely dry during the growing season. Reduce to once a month or less in winter. Overwatering causes soft, mushy stems and root rot.",temp:"Prefers 65–85°F (18–29°C) during growth. Cold-hardy to 25°F (-4°C) when kept dry in winter. Requires a cool, dry winter dormancy.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A large pot with drainage holes is essential.",fert:"Feed with a cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Use fresh cactus mix. Handle with care — spines are sharp.",growth:"A tall, columnar cactus with blue-green stems reaching 6–20 feet tall in nature. Grows 4–8 inches per year under ideal conditions. Features 6–8 prominent ribs with small spines. Produces large, fragrant white flowers at night on mature specimens. One of the fastest-growing columnar cacti.",problems:["Very fast-growing for a cactus; may need staking if it leans","Soft or mushy stems indicate overwatering; cut away affected tissue","Can grow very tall indoors; prune the top to control height","Mealybugs may hide in the rib crevices; treat with alcohol swabs"],tox:"Contains mescaline, a psychoactive compound. Toxic if ingested. Keep away from pets and children. Legality varies by region.",prop:"Propagate from cuttings. Cut a section of stem, let it callus for 1–2 weeks, then plant in dry cactus mix. Water sparingly until roots establish. Can also be grown from seed."},
{id:430,cn:"Euphorbia trigona",la:"African Milk Tree",light:"Requires bright, indirect light for 4–6 hours daily. An east- or south-facing window is ideal. Tolerates some direct morning sun. Too much intense afternoon sun can cause scorching.",water:"Water every 2–3 weeks when soil is completely dry. Reduce significantly in winter. Overwatering causes soft, mushy stems and root rot.",temp:"Prefers 65–80°F (18–27°C). Protect from temperatures below 50°F (10°C) and cold drafts. Not cold-hardy.",soil:"Use a fast-draining cactus mix with added perlite. Ensure the pot has drainage holes.",fert:"Feed with a diluted cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Handle with care — spines are sharp and the sap is irritating. Use thick gloves.",growth:"A fast-growing, columnar succulent with triangular stems and small, paired leaves along the edges. Can reach 6–8 feet indoors. The 'Rubra' cultivar has red-tinted stems. Growth is moderate to fast. Despite the common name, it is not a true cactus but a Euphorbia.",problems:["The milky white sap is highly irritating to skin and eyes; wear gloves when pruning or handling","Grows fast and may need staking or a heavy pot to prevent tipping","Leggy growth indicates insufficient light; move to brighter light","Mealybugs may hide at stem joints"],tox:"The milky white sap is highly toxic and irritating to skin, eyes, and mucous membranes. Toxic to pets and humans if ingested. Wear gloves when handling.",prop:"Propagate from stem cuttings. Cut a 4–6 inch section, rinse off the milky sap, and let it callus for 1–2 weeks. Plant in dry cactus mix. Water sparingly until roots establish."},
{id:431,cn:"Echinopsis pachanoi",la:"San Pedro Cactus",light:"Requires full sun for at least 6–8 hours daily. A south-facing window or outdoor location is ideal. Acclimate gradually to prevent sunburn.",water:"Water every 2–3 weeks when soil is completely dry during the growing season. Reduce to once a month or less in winter. Overwatering causes soft, mushy stems and root rot.",temp:"Prefers 65–85°F (18–29°C) during growth. Cold-hardy to 25°F (-4°C) when kept dry in winter. Requires a cool, dry winter dormancy.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A large pot with drainage holes is essential.",fert:"Feed with a cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Use fresh cactus mix. Handle with care — spines are sharp.",growth:"A tall, columnar cactus with blue-green stems reaching 6–20 feet tall in nature. Grows 4–8 inches per year under ideal conditions. Features 6–8 prominent ribs with small spines. Produces large, fragrant white flowers at night on mature specimens.",problems:["Very fast-growing for a cactus; may need staking if it leans","Soft or mushy stems indicate overwatering; cut away affected tissue","Can grow very tall indoors; prune the top to control height","Mealybugs may hide in the rib crevices; treat with alcohol swabs"],tox:"Contains mescaline, a psychoactive compound. Toxic if ingested. Keep away from pets and children. Legality varies by region.",prop:"Propagate from cuttings. Cut a section of stem, let it callus for 1–2 weeks, then plant in dry cactus mix. Water sparingly until roots establish."},
{id:604,cn:"Astrophytum myriostigma",la:"Bishop's Cap Cactus",light:"Requires bright, indirect light for 4–6 hours daily. An east-facing window is ideal. Tolerates some gentle morning sun. Too much intense sun can cause scarring.",water:"Water every 2–3 weeks when soil is completely dry. Reduce to once a month or less in winter. Overwatering causes soft, mushy body and root rot.",temp:"Prefers 65–80°F (18–27°C) during growth. Cold-hardy to 20°F (-7°C) when kept completely dry in winter.",soil:"Use a very fast-draining cactus mix with extra perlite or pumice. Excellent drainage is critical. A small pot that fits the plant snugly is ideal.",fert:"Feed with a diluted cactus fertilizer once in spring and once in summer. Do not fertilize in fall or winter.",rep:"Repot every 2–3 years in spring. Handle carefully — the plant has no spines but the body can scar easily. Use fresh cactus mix.",growth:"A spineless, globe-shaped cactus with 5 prominent ribs and a body covered in white, felt-like spots (flocking). The spots give it a starry, speckled appearance. Reaches 4–6 inches tall and wide over many years. Growth is slow. Produces yellow flowers at the apex on mature specimens. The var. nudum form lacks the white spots.",problems:["The white spots are natural flocking, not pests or disease","Scars on the body do not heal; handle with care","Soft or mushy body indicates overwatering; stop immediately","Flowering takes many years; be patient","Mealybugs may hide in the rib crevices; treat with alcohol swabs"],tox:"Non-toxic to humans and pets. Safe for households with animals.",prop:"Propagate from seed. Sow seeds in moist cactus mix and keep warm. Germination takes 2–4 weeks. Seedlings grow slowly. This species does not produce offsets."}
];

// Add new plants
const existingIds = new Set(entries.map(e => {
  const m = e.match(/\{id:(\d+)/);
  return m ? parseInt(m[1]) : -1;
}));

let added = 0;
for (const np of newPlants) {
  if (existingIds.has(np.id)) {
    console.log('Skip: ID', np.id, 'already exists');
    continue;
  }
  // Build entry string
  const props = Object.entries(np).map(([k,v]) => {
    if (Array.isArray(v)) return k + ':["' + v.join('","').replace(/"/g, '\\"') + '"]';
    if (typeof v === 'string') return k + ':"' + v.replace(/"/g, '\\"') + '"';
    return k + ':' + v;
  }).join(',');
  entries.push('{' + props + '}');
  added++;
}
console.log('Added', added, 'new plants');

// Sort by ID
const getId = e => parseInt(e.match(/\{id:(\d+)/)[1]);
entries.sort((a, b) => getId(a) - getId(b));

// Rebuild
const rebuilt = entries.map((e, i) => i < entries.length - 1 ? e + ',' : e).join('\n');
const newContent = content.replace(
  /const plants=\[[\s\S]*?\];/,
  'const plants=[\n' + rebuilt + '\n];'
);

fs.writeFileSync('index.html', newContent, 'utf-8');

// Verify
const v = fs.readFileSync('index.html', 'utf-8');
const vm = v.match(/const plants=\[([\s\S]*?)\];/);
try {
  const plants = new Function('return [' + vm[1] + ']')();
  console.log('SUCCESS:', plants.length, 'plants');
  console.log('IDs:', plants.map(p => p.id).join(', '));
} catch (e) {
  console.log('VERIFY ERROR:', e.message);
  process.exit(1);
}
